hid_dim: 128
batch_size: 20
epochs: 30
shot_num: 1
prompt_graph_token_num: 10
supervised_and_finetune_lr: 0.02
supervised_and_finetune_weight_decay: 0.0004
finetune_lr: 0.02
finetune_weight_decay: 0.00045
pg_lr: 0.001
pg_weight_decay: 0.001
answer_lr: 0.002
answer_weight_decay: 0.00001
num_layer: 2
projector_dropout_ratio: 0.2
temperature: 2.0
seed: 42
prompt_tune_epochs: 30
answer_tune_epochs: 30
train_val_acc_diff_tol: 1
val_acc_threshold: 1
warmup_epochs: 1
pf_warmup_epochs: 20
supervised_epochs: 60
finetune_epochs: 100
answer_tune_epochs: 20