hid_dim: 128
batch_size: 16
epochs: 50
shot_num: 10
prompt_graph_token_num: 10
supervised_and_finetune_lr: 0.0005
supervised_and_finetune_weight_decay: 0.00001
pg_lr: 0.001
pg_weight_decay: 0.001
answer_lr: 0.001
answer_weight_decay: 0.001
num_layer: 2
projector_dropout_ratio: 0.2
temperature: 2.0
seed: 42
prompt_tune_epochs: 50
answer_tune_epochs: 50
train_val_acc_diff_tol: 1
val_acc_threshold: 1
warmup_epochs: 1