hid_dim: 128
batch_size: 16
epochs: 10
shot_num: 10
prompt_graph_token_num: 10
projector_lr: 0.01
projector_weight_decay: 0.01
projector_tune_lr: 0.001
projector_tune_weight_decay: 0.01
pg_lr: 0.001
pg_weight_decay: 0.001
text_prompt_lr: 0.001
text_prompt_weight_decay: 0.001
num_layer: 2
projector_dropout_ratio: 0.5
temperature: 5.0
seed: 42
text_prompt_start_vocab: 'this enzyme is'
projector_epochs: 2001
projector_train_eval_diff_threshold: 0.1
projector_train_modular: 100
projector_tune_epochs: 30
prompt_tune_epochs: 30
train_val_acc_diff_tol: 0.15
val_acc_threshold: 1
warmup_epochs: 1