hid_dim: 128
batch_size: 16
epochs: 20
shot_num: 10
prompt_graph_token_num: 10
projector_lr: 0.01
projector_weight_decay: 0.1
projector_tune_lr: 0.0005
projector_tune_weight_decay: 0.1
pg_lr: 0.001
pg_weight_decay: 0.001
text_prompt_lr: 0.001
text_prompt_weight_decay: 0.001
num_layer: 2
projector_dropout_ratio: 0.2
temperature: 2.0
seed: 42
text_prompt_start_vocab: 'this protein is'
projector_epochs: 2001
projector_train_eval_diff_threshold: 0.1
projector_train_modular: 100
projector_tune_epochs: 50
prompt_tune_epochs: 50
train_val_acc_diff_tol: 0.12
val_acc_threshold: 1
warmup_epochs: 1